name: Publish SDK

on:
  push:
    branches:
      - main  
  release:
    types: [published, edited, created]
  workflow_dispatch: {}

jobs:
  publish-github:
    name: Publish to GitHub Packages
    uses: ./.github/workflows/common-publish.yml
    with:
      registry-url: "https://npm.pkg.github.com"
      node-auth-token: ${{ secrets.GITHUB_TOKEN }}
